on:
  push:
  workflow_dispatch:
jobs:
  information_display:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice::Ceci est un notice"
      - run: echo "::warning::Ceci est un warning"
      - run: echo "::error::Ceci est une erreur"
