on:
  push:
  workflow_dispatch:
jobs:
  prepare_test:
    runs-on: ubuntu-latest
    outputs:
      HOST: ${{ steps.lolhost.outputs.HOST }}
      DATABASE: ${{ steps.loldatabase.outputs.DATABASE }}
    steps:
      - name: "Allocate a new host"
        id: lolhost
        run: |
          echo HOST=srv1 >> $GITHUB_OUTPUT
      - name: "Allocate a new host"
        id: loldatabase
        run: |
          echo DATABASE=prep002 >> $GITHUB_OUTPUT
  # display_info:
  #   runs-on: ubuntu-latest
  #   steps:
  #       run: echo
      

