on:
  push:
  workflow_dispatch:
jobs:
  testing_phase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repository
        uses: actions/checkout@v3
        with:
          repository: tldr-pages/tldr-python-client
          ref: "3.1.0"
      - name: Save test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html
      - run: |
              pip install -r requirements.txt
              pip install pytest
              pip install pytest-html
              pytest