on:
  push:
  workflow_dispatch:
jobs:
  testing_phase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout another repository
        uses: actions/checkout@v3
        with:
          repository: tldr-pages/tldr-python-client
          ref: "3.1.0"
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: pip install pytest-html
      - run: python -m pytest --html=report.html --self-contained-html
      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html