on:
  push:
  workflow_dispatch:
jobs:
  testing_phase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: poetry install
      - run: poetry run python -m pytest
      - run: poetry build
      - name: Save test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sauvegarde-build?
          path: dist/



      # - run: pip install -r requirements.txt
      # - run: pip install pytest
      # - run: pip install pytest-html